//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4 /Users/abdullin/MessageContracts.g 2012-07-26 13:04:59

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 168, 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;
using ConditionalAttribute = System.Diagnostics.ConditionalAttribute;


using Antlr.Runtime.Tree;
using RewriteRuleITokenStream = Antlr.Runtime.Tree.RewriteRuleTokenStream;

namespace  MessageContracts 
{
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4")]
[System.CLSCompliant(false)]
public partial class MessageContractsParser : Antlr.Runtime.Parser
{
	internal static readonly string[] tokenNames = new string[] {
		"<invalid>", "<EOR>", "<DOWN>", "<UP>", "BlockToken", "COMMENT", "CONST", "CommandToken", "DisctionaryToken", "ESC_SEQ", "EXPLICIT", "EXTERN", "EntityDefinition", "EventToken", "ExternToken", "FragmentEntry", "FragmentGroup", "FragmentReference", "HEX_DIGIT", "ID", "IF", "INT", "INTERFACE", "MemberToken", "Modifier", "ModifierDefinition", "NAMESPACE", "NamespaceToken", "OCTAL_ESC", "STRING", "StringRepresentationToken", "TypeToken", "UNICODE_ESC", "USING", "UsingToken", "WS", "'('", "')'", "','", "'.'", "';'", "'='", "'{'", "'}'"
	};
	public const int EOF=-1;
	public const int T__36=36;
	public const int T__37=37;
	public const int T__38=38;
	public const int T__39=39;
	public const int T__40=40;
	public const int T__41=41;
	public const int T__42=42;
	public const int T__43=43;
	public const int BlockToken=4;
	public const int COMMENT=5;
	public const int CONST=6;
	public const int CommandToken=7;
	public const int DisctionaryToken=8;
	public const int ESC_SEQ=9;
	public const int EXPLICIT=10;
	public const int EXTERN=11;
	public const int EntityDefinition=12;
	public const int EventToken=13;
	public const int ExternToken=14;
	public const int FragmentEntry=15;
	public const int FragmentGroup=16;
	public const int FragmentReference=17;
	public const int HEX_DIGIT=18;
	public const int ID=19;
	public const int IF=20;
	public const int INT=21;
	public const int INTERFACE=22;
	public const int MemberToken=23;
	public const int Modifier=24;
	public const int ModifierDefinition=25;
	public const int NAMESPACE=26;
	public const int NamespaceToken=27;
	public const int OCTAL_ESC=28;
	public const int STRING=29;
	public const int StringRepresentationToken=30;
	public const int TypeToken=31;
	public const int UNICODE_ESC=32;
	public const int USING=33;
	public const int UsingToken=34;
	public const int WS=35;

	#if ANTLR_DEBUG
		private static readonly bool[] decisionCanBacktrack =
			new bool[]
			{
				false, // invalid decision
				false, false, false, false, false, false, false, false, false, false, 
				false
			};
	#else
		private static readonly bool[] decisionCanBacktrack = new bool[0];
	#endif
	public MessageContractsParser(ITokenStream input)
		: this(input, new RecognizerSharedState())
	{
	}
	public MessageContractsParser(ITokenStream input, RecognizerSharedState state)
		: base(input, state)
	{
		OnCreated();
	}
	private ITreeAdaptor adaptor;

	public ITreeAdaptor TreeAdaptor
	{
		get
		{
			return adaptor;
		}

		set
		{
			this.adaptor = value;
		}
	}

	public override string[] TokenNames { get { return MessageContractsParser.tokenNames; } }
	public override string GrammarFileName { get { return "/Users/abdullin/MessageContracts.g"; } }


	[Conditional("ANTLR_TRACE")]
	protected virtual void OnCreated() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule(string ruleName, int ruleIndex) {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule(string ruleName, int ruleIndex) {}

	#region Rules

	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_program() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_program() {}

	// $ANTLR start "program"
	// /Users/abdullin/MessageContracts.g:31:1: program : ( declaration )+ ;
	[GrammarRule("program")]
	private AstParserRuleReturnScope<object, IToken> program()
	{
		EnterRule_program();
		EnterRule("program", 1);
		TraceIn("program", 1);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    AstParserRuleReturnScope<object, IToken> declaration1 = default(AstParserRuleReturnScope<object, IToken>);


		try { DebugEnterRule(GrammarFileName, "program");
		DebugLocation(31, 1);
		try
		{
			// /Users/abdullin/MessageContracts.g:32:2: ( ( declaration )+ )
			DebugEnterAlt(1);
			// /Users/abdullin/MessageContracts.g:32:4: ( declaration )+
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(32, 4);
			// /Users/abdullin/MessageContracts.g:32:4: ( declaration )+
			int cnt1=0;
			try { DebugEnterSubRule(1);
			while (true)
			{
				int alt1=2;
				try { DebugEnterDecision(1, decisionCanBacktrack[1]);
				int LA1_0 = input.LA(1);

				if ((LA1_0==CONST||LA1_0==EXTERN||(LA1_0>=ID && LA1_0<=IF)||LA1_0==INTERFACE||LA1_0==NAMESPACE||LA1_0==USING))
				{
					alt1 = 1;
				}


				} finally { DebugExitDecision(1); }
				switch (alt1)
				{
				case 1:
					DebugEnterAlt(1);
					// /Users/abdullin/MessageContracts.g:32:4: declaration
					{
					DebugLocation(32, 4);
					PushFollow(Follow._declaration_in_program117);
					declaration1=declaration();
					PopFollow();

					adaptor.AddChild(root_0, declaration1.Tree);

					}
					break;

				default:
					if (cnt1 >= 1)
						goto loop1;

					EarlyExitException eee1 = new EarlyExitException( 1, input );
					DebugRecognitionException(eee1);
					throw eee1;
				}
				cnt1++;
			}
			loop1:
				;

			} finally { DebugExitSubRule(1); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("program", 1);
			LeaveRule("program", 1);
			LeaveRule_program();
	    }
	 	DebugLocation(33, 1);
		} finally { DebugExitRule(GrammarFileName, "program"); }
		return retval;

	}
	// $ANTLR end "program"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_declaration() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_declaration() {}

	// $ANTLR start "declaration"
	// /Users/abdullin/MessageContracts.g:35:1: declaration : ( modifier_declaration | frag_declaration | type_declaration | entity_declaration | namespace_declaration | extern_declaration | using_declaration );
	[GrammarRule("declaration")]
	private AstParserRuleReturnScope<object, IToken> declaration()
	{
		EnterRule_declaration();
		EnterRule("declaration", 2);
		TraceIn("declaration", 2);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    AstParserRuleReturnScope<object, IToken> modifier_declaration2 = default(AstParserRuleReturnScope<object, IToken>);
	    AstParserRuleReturnScope<object, IToken> frag_declaration3 = default(AstParserRuleReturnScope<object, IToken>);
	    AstParserRuleReturnScope<object, IToken> type_declaration4 = default(AstParserRuleReturnScope<object, IToken>);
	    AstParserRuleReturnScope<object, IToken> entity_declaration5 = default(AstParserRuleReturnScope<object, IToken>);
	    AstParserRuleReturnScope<object, IToken> namespace_declaration6 = default(AstParserRuleReturnScope<object, IToken>);
	    AstParserRuleReturnScope<object, IToken> extern_declaration7 = default(AstParserRuleReturnScope<object, IToken>);
	    AstParserRuleReturnScope<object, IToken> using_declaration8 = default(AstParserRuleReturnScope<object, IToken>);


		try { DebugEnterRule(GrammarFileName, "declaration");
		DebugLocation(35, 1);
		try
		{
			// /Users/abdullin/MessageContracts.g:36:2: ( modifier_declaration | frag_declaration | type_declaration | entity_declaration | namespace_declaration | extern_declaration | using_declaration )
			int alt2=7;
			try { DebugEnterDecision(2, decisionCanBacktrack[2]);
			switch (input.LA(1))
			{
			case IF:
				{
				alt2 = 1;
				}
				break;
			case CONST:
				{
				alt2 = 2;
				}
				break;
			case ID:
				{
				alt2 = 3;
				}
				break;
			case INTERFACE:
				{
				alt2 = 4;
				}
				break;
			case NAMESPACE:
				{
				alt2 = 5;
				}
				break;
			case EXTERN:
				{
				alt2 = 6;
				}
				break;
			case USING:
				{
				alt2 = 7;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 2, 0, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(2); }
			switch (alt2)
			{
			case 1:
				DebugEnterAlt(1);
				// /Users/abdullin/MessageContracts.g:36:4: modifier_declaration
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(36, 4);
				PushFollow(Follow._modifier_declaration_in_declaration130);
				modifier_declaration2=modifier_declaration();
				PopFollow();

				adaptor.AddChild(root_0, modifier_declaration2.Tree);

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// /Users/abdullin/MessageContracts.g:37:4: frag_declaration
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(37, 4);
				PushFollow(Follow._frag_declaration_in_declaration135);
				frag_declaration3=frag_declaration();
				PopFollow();

				adaptor.AddChild(root_0, frag_declaration3.Tree);

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// /Users/abdullin/MessageContracts.g:38:4: type_declaration
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(38, 4);
				PushFollow(Follow._type_declaration_in_declaration140);
				type_declaration4=type_declaration();
				PopFollow();

				adaptor.AddChild(root_0, type_declaration4.Tree);

				}
				break;
			case 4:
				DebugEnterAlt(4);
				// /Users/abdullin/MessageContracts.g:39:4: entity_declaration
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(39, 4);
				PushFollow(Follow._entity_declaration_in_declaration145);
				entity_declaration5=entity_declaration();
				PopFollow();

				adaptor.AddChild(root_0, entity_declaration5.Tree);

				}
				break;
			case 5:
				DebugEnterAlt(5);
				// /Users/abdullin/MessageContracts.g:40:4: namespace_declaration
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(40, 4);
				PushFollow(Follow._namespace_declaration_in_declaration150);
				namespace_declaration6=namespace_declaration();
				PopFollow();

				adaptor.AddChild(root_0, namespace_declaration6.Tree);

				}
				break;
			case 6:
				DebugEnterAlt(6);
				// /Users/abdullin/MessageContracts.g:41:4: extern_declaration
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(41, 4);
				PushFollow(Follow._extern_declaration_in_declaration156);
				extern_declaration7=extern_declaration();
				PopFollow();

				adaptor.AddChild(root_0, extern_declaration7.Tree);

				}
				break;
			case 7:
				DebugEnterAlt(7);
				// /Users/abdullin/MessageContracts.g:42:4: using_declaration
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(42, 4);
				PushFollow(Follow._using_declaration_in_declaration161);
				using_declaration8=using_declaration();
				PopFollow();

				adaptor.AddChild(root_0, using_declaration8.Tree);

				}
				break;

			}
			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("declaration", 2);
			LeaveRule("declaration", 2);
			LeaveRule_declaration();
	    }
	 	DebugLocation(43, 1);
		} finally { DebugExitRule(GrammarFileName, "declaration"); }
		return retval;

	}
	// $ANTLR end "declaration"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_namespace_declaration() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_namespace_declaration() {}

	// $ANTLR start "namespace_declaration"
	// /Users/abdullin/MessageContracts.g:45:1: namespace_declaration : NAMESPACE ( ID ( '.' ID )* ) ';' -> ^( NamespaceToken ( ID )* ) ;
	[GrammarRule("namespace_declaration")]
	private AstParserRuleReturnScope<object, IToken> namespace_declaration()
	{
		EnterRule_namespace_declaration();
		EnterRule("namespace_declaration", 3);
		TraceIn("namespace_declaration", 3);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    IToken NAMESPACE9 = default(IToken);
	    IToken ID10 = default(IToken);
	    IToken char_literal11 = default(IToken);
	    IToken ID12 = default(IToken);
	    IToken char_literal13 = default(IToken);

	    object NAMESPACE9_tree = default(object);
	    object ID10_tree = default(object);
	    object char_literal11_tree = default(object);
	    object ID12_tree = default(object);
	    object char_literal13_tree = default(object);
	    RewriteRuleITokenStream stream_40=new RewriteRuleITokenStream(adaptor,"token 40");
	    RewriteRuleITokenStream stream_ID=new RewriteRuleITokenStream(adaptor,"token ID");
	    RewriteRuleITokenStream stream_39=new RewriteRuleITokenStream(adaptor,"token 39");
	    RewriteRuleITokenStream stream_NAMESPACE=new RewriteRuleITokenStream(adaptor,"token NAMESPACE");

		try { DebugEnterRule(GrammarFileName, "namespace_declaration");
		DebugLocation(45, 28);
		try
		{
			// /Users/abdullin/MessageContracts.g:46:5: ( NAMESPACE ( ID ( '.' ID )* ) ';' -> ^( NamespaceToken ( ID )* ) )
			DebugEnterAlt(1);
			// /Users/abdullin/MessageContracts.g:46:7: NAMESPACE ( ID ( '.' ID )* ) ';'
			{
			DebugLocation(46, 7);
			NAMESPACE9=(IToken)Match(input,NAMESPACE,Follow._NAMESPACE_in_namespace_declaration175);  
			stream_NAMESPACE.Add(NAMESPACE9);

			DebugLocation(46, 17);
			// /Users/abdullin/MessageContracts.g:46:17: ( ID ( '.' ID )* )
			DebugEnterAlt(1);
			// /Users/abdullin/MessageContracts.g:46:18: ID ( '.' ID )*
			{
			DebugLocation(46, 18);
			ID10=(IToken)Match(input,ID,Follow._ID_in_namespace_declaration178);  
			stream_ID.Add(ID10);

			DebugLocation(46, 21);
			// /Users/abdullin/MessageContracts.g:46:21: ( '.' ID )*
			try { DebugEnterSubRule(3);
			while (true)
			{
				int alt3=2;
				try { DebugEnterDecision(3, decisionCanBacktrack[3]);
				int LA3_0 = input.LA(1);

				if ((LA3_0==39))
				{
					alt3 = 1;
				}


				} finally { DebugExitDecision(3); }
				switch ( alt3 )
				{
				case 1:
					DebugEnterAlt(1);
					// /Users/abdullin/MessageContracts.g:46:22: '.' ID
					{
					DebugLocation(46, 22);
					char_literal11=(IToken)Match(input,39,Follow._39_in_namespace_declaration181);  
					stream_39.Add(char_literal11);

					DebugLocation(46, 26);
					ID12=(IToken)Match(input,ID,Follow._ID_in_namespace_declaration183);  
					stream_ID.Add(ID12);


					}
					break;

				default:
					goto loop3;
				}
			}

			loop3:
				;

			} finally { DebugExitSubRule(3); }


			}

			DebugLocation(46, 32);
			char_literal13=(IToken)Match(input,40,Follow._40_in_namespace_declaration188);  
			stream_40.Add(char_literal13);



			{
			// AST REWRITE
			// elements: ID
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 47:5: -> ^( NamespaceToken ( ID )* )
			{
				DebugLocation(47, 8);
				// /Users/abdullin/MessageContracts.g:47:8: ^( NamespaceToken ( ID )* )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(47, 10);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(NamespaceToken, "NamespaceToken"), root_1);

				DebugLocation(47, 25);
				// /Users/abdullin/MessageContracts.g:47:25: ( ID )*
				while ( stream_ID.HasNext )
				{
					DebugLocation(47, 25);
					adaptor.AddChild(root_1, stream_ID.NextNode());

				}
				stream_ID.Reset();

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("namespace_declaration", 3);
			LeaveRule("namespace_declaration", 3);
			LeaveRule_namespace_declaration();
	    }
	 	DebugLocation(47, 28);
		} finally { DebugExitRule(GrammarFileName, "namespace_declaration"); }
		return retval;

	}
	// $ANTLR end "namespace_declaration"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_using_declaration() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_using_declaration() {}

	// $ANTLR start "using_declaration"
	// /Users/abdullin/MessageContracts.g:49:1: using_declaration : USING ( ID ( '.' ID )* ) ';' -> ^( UsingToken ( ID )* ) ;
	[GrammarRule("using_declaration")]
	private AstParserRuleReturnScope<object, IToken> using_declaration()
	{
		EnterRule_using_declaration();
		EnterRule("using_declaration", 4);
		TraceIn("using_declaration", 4);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    IToken USING14 = default(IToken);
	    IToken ID15 = default(IToken);
	    IToken char_literal16 = default(IToken);
	    IToken ID17 = default(IToken);
	    IToken char_literal18 = default(IToken);

	    object USING14_tree = default(object);
	    object ID15_tree = default(object);
	    object char_literal16_tree = default(object);
	    object ID17_tree = default(object);
	    object char_literal18_tree = default(object);
	    RewriteRuleITokenStream stream_USING=new RewriteRuleITokenStream(adaptor,"token USING");
	    RewriteRuleITokenStream stream_40=new RewriteRuleITokenStream(adaptor,"token 40");
	    RewriteRuleITokenStream stream_ID=new RewriteRuleITokenStream(adaptor,"token ID");
	    RewriteRuleITokenStream stream_39=new RewriteRuleITokenStream(adaptor,"token 39");

		try { DebugEnterRule(GrammarFileName, "using_declaration");
		DebugLocation(49, 24);
		try
		{
			// /Users/abdullin/MessageContracts.g:50:5: ( USING ( ID ( '.' ID )* ) ';' -> ^( UsingToken ( ID )* ) )
			DebugEnterAlt(1);
			// /Users/abdullin/MessageContracts.g:50:7: USING ( ID ( '.' ID )* ) ';'
			{
			DebugLocation(50, 7);
			USING14=(IToken)Match(input,USING,Follow._USING_in_using_declaration218);  
			stream_USING.Add(USING14);

			DebugLocation(50, 13);
			// /Users/abdullin/MessageContracts.g:50:13: ( ID ( '.' ID )* )
			DebugEnterAlt(1);
			// /Users/abdullin/MessageContracts.g:50:14: ID ( '.' ID )*
			{
			DebugLocation(50, 14);
			ID15=(IToken)Match(input,ID,Follow._ID_in_using_declaration221);  
			stream_ID.Add(ID15);

			DebugLocation(50, 17);
			// /Users/abdullin/MessageContracts.g:50:17: ( '.' ID )*
			try { DebugEnterSubRule(4);
			while (true)
			{
				int alt4=2;
				try { DebugEnterDecision(4, decisionCanBacktrack[4]);
				int LA4_0 = input.LA(1);

				if ((LA4_0==39))
				{
					alt4 = 1;
				}


				} finally { DebugExitDecision(4); }
				switch ( alt4 )
				{
				case 1:
					DebugEnterAlt(1);
					// /Users/abdullin/MessageContracts.g:50:18: '.' ID
					{
					DebugLocation(50, 18);
					char_literal16=(IToken)Match(input,39,Follow._39_in_using_declaration224);  
					stream_39.Add(char_literal16);

					DebugLocation(50, 22);
					ID17=(IToken)Match(input,ID,Follow._ID_in_using_declaration226);  
					stream_ID.Add(ID17);


					}
					break;

				default:
					goto loop4;
				}
			}

			loop4:
				;

			} finally { DebugExitSubRule(4); }


			}

			DebugLocation(50, 28);
			char_literal18=(IToken)Match(input,40,Follow._40_in_using_declaration231);  
			stream_40.Add(char_literal18);



			{
			// AST REWRITE
			// elements: ID
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 51:5: -> ^( UsingToken ( ID )* )
			{
				DebugLocation(51, 8);
				// /Users/abdullin/MessageContracts.g:51:8: ^( UsingToken ( ID )* )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(51, 10);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(UsingToken, "UsingToken"), root_1);

				DebugLocation(51, 21);
				// /Users/abdullin/MessageContracts.g:51:21: ( ID )*
				while ( stream_ID.HasNext )
				{
					DebugLocation(51, 21);
					adaptor.AddChild(root_1, stream_ID.NextNode());

				}
				stream_ID.Reset();

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("using_declaration", 4);
			LeaveRule("using_declaration", 4);
			LeaveRule_using_declaration();
	    }
	 	DebugLocation(51, 24);
		} finally { DebugExitRule(GrammarFileName, "using_declaration"); }
		return retval;

	}
	// $ANTLR end "using_declaration"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_frag_declaration() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_frag_declaration() {}

	// $ANTLR start "frag_declaration"
	// /Users/abdullin/MessageContracts.g:54:1: frag_declaration : CONST ID '=' ID ID ';' -> ^( FragmentEntry ID ID ID ) ;
	[GrammarRule("frag_declaration")]
	private AstParserRuleReturnScope<object, IToken> frag_declaration()
	{
		EnterRule_frag_declaration();
		EnterRule("frag_declaration", 5);
		TraceIn("frag_declaration", 5);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    IToken CONST19 = default(IToken);
	    IToken ID20 = default(IToken);
	    IToken char_literal21 = default(IToken);
	    IToken ID22 = default(IToken);
	    IToken ID23 = default(IToken);
	    IToken char_literal24 = default(IToken);

	    object CONST19_tree = default(object);
	    object ID20_tree = default(object);
	    object char_literal21_tree = default(object);
	    object ID22_tree = default(object);
	    object ID23_tree = default(object);
	    object char_literal24_tree = default(object);
	    RewriteRuleITokenStream stream_41=new RewriteRuleITokenStream(adaptor,"token 41");
	    RewriteRuleITokenStream stream_40=new RewriteRuleITokenStream(adaptor,"token 40");
	    RewriteRuleITokenStream stream_ID=new RewriteRuleITokenStream(adaptor,"token ID");
	    RewriteRuleITokenStream stream_CONST=new RewriteRuleITokenStream(adaptor,"token CONST");

		try { DebugEnterRule(GrammarFileName, "frag_declaration");
		DebugLocation(54, 54);
		try
		{
			// /Users/abdullin/MessageContracts.g:55:2: ( CONST ID '=' ID ID ';' -> ^( FragmentEntry ID ID ID ) )
			DebugEnterAlt(1);
			// /Users/abdullin/MessageContracts.g:55:4: CONST ID '=' ID ID ';'
			{
			DebugLocation(55, 4);
			CONST19=(IToken)Match(input,CONST,Follow._CONST_in_frag_declaration255);  
			stream_CONST.Add(CONST19);

			DebugLocation(55, 10);
			ID20=(IToken)Match(input,ID,Follow._ID_in_frag_declaration257);  
			stream_ID.Add(ID20);

			DebugLocation(55, 13);
			char_literal21=(IToken)Match(input,41,Follow._41_in_frag_declaration259);  
			stream_41.Add(char_literal21);

			DebugLocation(55, 17);
			ID22=(IToken)Match(input,ID,Follow._ID_in_frag_declaration261);  
			stream_ID.Add(ID22);

			DebugLocation(55, 20);
			ID23=(IToken)Match(input,ID,Follow._ID_in_frag_declaration263);  
			stream_ID.Add(ID23);

			DebugLocation(55, 23);
			char_literal24=(IToken)Match(input,40,Follow._40_in_frag_declaration265);  
			stream_40.Add(char_literal24);



			{
			// AST REWRITE
			// elements: ID, ID, ID
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 55:27: -> ^( FragmentEntry ID ID ID )
			{
				DebugLocation(55, 30);
				// /Users/abdullin/MessageContracts.g:55:30: ^( FragmentEntry ID ID ID )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(55, 32);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(FragmentEntry, "FragmentEntry"), root_1);

				DebugLocation(55, 46);
				adaptor.AddChild(root_1, stream_ID.NextNode());
				DebugLocation(55, 49);
				adaptor.AddChild(root_1, stream_ID.NextNode());
				DebugLocation(55, 52);
				adaptor.AddChild(root_1, stream_ID.NextNode());

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("frag_declaration", 5);
			LeaveRule("frag_declaration", 5);
			LeaveRule_frag_declaration();
	    }
	 	DebugLocation(55, 54);
		} finally { DebugExitRule(GrammarFileName, "frag_declaration"); }
		return retval;

	}
	// $ANTLR end "frag_declaration"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_modifier_declaration() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_modifier_declaration() {}

	// $ANTLR start "modifier_declaration"
	// /Users/abdullin/MessageContracts.g:57:1: modifier_declaration : IF Modifier '=' ID ( ',' ID )* ';' -> ^( ModifierDefinition Modifier ( ID )* ) ;
	[GrammarRule("modifier_declaration")]
	private AstParserRuleReturnScope<object, IToken> modifier_declaration()
	{
		EnterRule_modifier_declaration();
		EnterRule("modifier_declaration", 6);
		TraceIn("modifier_declaration", 6);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    IToken IF25 = default(IToken);
	    IToken Modifier26 = default(IToken);
	    IToken char_literal27 = default(IToken);
	    IToken ID28 = default(IToken);
	    IToken char_literal29 = default(IToken);
	    IToken ID30 = default(IToken);
	    IToken char_literal31 = default(IToken);

	    object IF25_tree = default(object);
	    object Modifier26_tree = default(object);
	    object char_literal27_tree = default(object);
	    object ID28_tree = default(object);
	    object char_literal29_tree = default(object);
	    object ID30_tree = default(object);
	    object char_literal31_tree = default(object);
	    RewriteRuleITokenStream stream_41=new RewriteRuleITokenStream(adaptor,"token 41");
	    RewriteRuleITokenStream stream_40=new RewriteRuleITokenStream(adaptor,"token 40");
	    RewriteRuleITokenStream stream_ID=new RewriteRuleITokenStream(adaptor,"token ID");
	    RewriteRuleITokenStream stream_Modifier=new RewriteRuleITokenStream(adaptor,"token Modifier");
	    RewriteRuleITokenStream stream_IF=new RewriteRuleITokenStream(adaptor,"token IF");
	    RewriteRuleITokenStream stream_38=new RewriteRuleITokenStream(adaptor,"token 38");

		try { DebugEnterRule(GrammarFileName, "modifier_declaration");
		DebugLocation(57, 73);
		try
		{
			// /Users/abdullin/MessageContracts.g:58:2: ( IF Modifier '=' ID ( ',' ID )* ';' -> ^( ModifierDefinition Modifier ( ID )* ) )
			DebugEnterAlt(1);
			// /Users/abdullin/MessageContracts.g:58:4: IF Modifier '=' ID ( ',' ID )* ';'
			{
			DebugLocation(58, 4);
			IF25=(IToken)Match(input,IF,Follow._IF_in_modifier_declaration292);  
			stream_IF.Add(IF25);

			DebugLocation(58, 7);
			Modifier26=(IToken)Match(input,Modifier,Follow._Modifier_in_modifier_declaration294);  
			stream_Modifier.Add(Modifier26);

			DebugLocation(58, 16);
			char_literal27=(IToken)Match(input,41,Follow._41_in_modifier_declaration296);  
			stream_41.Add(char_literal27);

			DebugLocation(58, 20);
			ID28=(IToken)Match(input,ID,Follow._ID_in_modifier_declaration298);  
			stream_ID.Add(ID28);

			DebugLocation(58, 23);
			// /Users/abdullin/MessageContracts.g:58:23: ( ',' ID )*
			try { DebugEnterSubRule(5);
			while (true)
			{
				int alt5=2;
				try { DebugEnterDecision(5, decisionCanBacktrack[5]);
				int LA5_0 = input.LA(1);

				if ((LA5_0==38))
				{
					alt5 = 1;
				}


				} finally { DebugExitDecision(5); }
				switch ( alt5 )
				{
				case 1:
					DebugEnterAlt(1);
					// /Users/abdullin/MessageContracts.g:58:24: ',' ID
					{
					DebugLocation(58, 24);
					char_literal29=(IToken)Match(input,38,Follow._38_in_modifier_declaration301);  
					stream_38.Add(char_literal29);

					DebugLocation(58, 28);
					ID30=(IToken)Match(input,ID,Follow._ID_in_modifier_declaration303);  
					stream_ID.Add(ID30);


					}
					break;

				default:
					goto loop5;
				}
			}

			loop5:
				;

			} finally { DebugExitSubRule(5); }

			DebugLocation(58, 33);
			char_literal31=(IToken)Match(input,40,Follow._40_in_modifier_declaration307);  
			stream_40.Add(char_literal31);



			{
			// AST REWRITE
			// elements: Modifier, ID
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 58:37: -> ^( ModifierDefinition Modifier ( ID )* )
			{
				DebugLocation(58, 40);
				// /Users/abdullin/MessageContracts.g:58:40: ^( ModifierDefinition Modifier ( ID )* )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(58, 42);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(ModifierDefinition, "ModifierDefinition"), root_1);

				DebugLocation(58, 61);
				adaptor.AddChild(root_1, stream_Modifier.NextNode());
				DebugLocation(58, 70);
				// /Users/abdullin/MessageContracts.g:58:70: ( ID )*
				while ( stream_ID.HasNext )
				{
					DebugLocation(58, 70);
					adaptor.AddChild(root_1, stream_ID.NextNode());

				}
				stream_ID.Reset();

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("modifier_declaration", 6);
			LeaveRule("modifier_declaration", 6);
			LeaveRule_modifier_declaration();
	    }
	 	DebugLocation(58, 73);
		} finally { DebugExitRule(GrammarFileName, "modifier_declaration"); }
		return retval;

	}
	// $ANTLR end "modifier_declaration"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_entity_declaration() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_entity_declaration() {}

	// $ANTLR start "entity_declaration"
	// /Users/abdullin/MessageContracts.g:60:1: entity_declaration : lc= INTERFACE ID block '{' ( declaration )* '}' -> ^( EntityDefinition[$lc,\"Block\"] ID block ( declaration )* ) ;
	[GrammarRule("entity_declaration")]
	private AstParserRuleReturnScope<object, IToken> entity_declaration()
	{
		EnterRule_entity_declaration();
		EnterRule("entity_declaration", 7);
		TraceIn("entity_declaration", 7);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    IToken lc = default(IToken);
	    IToken ID32 = default(IToken);
	    IToken char_literal34 = default(IToken);
	    IToken char_literal36 = default(IToken);
	    AstParserRuleReturnScope<object, IToken> block33 = default(AstParserRuleReturnScope<object, IToken>);
	    AstParserRuleReturnScope<object, IToken> declaration35 = default(AstParserRuleReturnScope<object, IToken>);

	    object lc_tree = default(object);
	    object ID32_tree = default(object);
	    object char_literal34_tree = default(object);
	    object char_literal36_tree = default(object);
	    RewriteRuleITokenStream stream_43=new RewriteRuleITokenStream(adaptor,"token 43");
	    RewriteRuleITokenStream stream_42=new RewriteRuleITokenStream(adaptor,"token 42");
	    RewriteRuleITokenStream stream_INTERFACE=new RewriteRuleITokenStream(adaptor,"token INTERFACE");
	    RewriteRuleITokenStream stream_ID=new RewriteRuleITokenStream(adaptor,"token ID");
	    RewriteRuleSubtreeStream stream_declaration=new RewriteRuleSubtreeStream(adaptor,"rule declaration");
	    RewriteRuleSubtreeStream stream_block=new RewriteRuleSubtreeStream(adaptor,"rule block");
		try { DebugEnterRule(GrammarFileName, "entity_declaration");
		DebugLocation(60, 58);
		try
		{
			// /Users/abdullin/MessageContracts.g:61:2: (lc= INTERFACE ID block '{' ( declaration )* '}' -> ^( EntityDefinition[$lc,\"Block\"] ID block ( declaration )* ) )
			DebugEnterAlt(1);
			// /Users/abdullin/MessageContracts.g:61:4: lc= INTERFACE ID block '{' ( declaration )* '}'
			{
			DebugLocation(61, 6);
			lc=(IToken)Match(input,INTERFACE,Follow._INTERFACE_in_entity_declaration331);  
			stream_INTERFACE.Add(lc);

			DebugLocation(61, 18);
			ID32=(IToken)Match(input,ID,Follow._ID_in_entity_declaration333);  
			stream_ID.Add(ID32);

			DebugLocation(61, 21);
			PushFollow(Follow._block_in_entity_declaration335);
			block33=block();
			PopFollow();

			stream_block.Add(block33.Tree);
			DebugLocation(61, 27);
			char_literal34=(IToken)Match(input,42,Follow._42_in_entity_declaration337);  
			stream_42.Add(char_literal34);

			DebugLocation(61, 31);
			// /Users/abdullin/MessageContracts.g:61:31: ( declaration )*
			try { DebugEnterSubRule(6);
			while (true)
			{
				int alt6=2;
				try { DebugEnterDecision(6, decisionCanBacktrack[6]);
				int LA6_0 = input.LA(1);

				if ((LA6_0==CONST||LA6_0==EXTERN||(LA6_0>=ID && LA6_0<=IF)||LA6_0==INTERFACE||LA6_0==NAMESPACE||LA6_0==USING))
				{
					alt6 = 1;
				}


				} finally { DebugExitDecision(6); }
				switch ( alt6 )
				{
				case 1:
					DebugEnterAlt(1);
					// /Users/abdullin/MessageContracts.g:61:31: declaration
					{
					DebugLocation(61, 31);
					PushFollow(Follow._declaration_in_entity_declaration339);
					declaration35=declaration();
					PopFollow();

					stream_declaration.Add(declaration35.Tree);

					}
					break;

				default:
					goto loop6;
				}
			}

			loop6:
				;

			} finally { DebugExitSubRule(6); }

			DebugLocation(61, 44);
			char_literal36=(IToken)Match(input,43,Follow._43_in_entity_declaration342);  
			stream_43.Add(char_literal36);



			{
			// AST REWRITE
			// elements: ID, declaration, block
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 62:2: -> ^( EntityDefinition[$lc,\"Block\"] ID block ( declaration )* )
			{
				DebugLocation(62, 5);
				// /Users/abdullin/MessageContracts.g:62:5: ^( EntityDefinition[$lc,\"Block\"] ID block ( declaration )* )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(62, 7);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(EntityDefinition, lc, "Block"), root_1);

				DebugLocation(62, 37);
				adaptor.AddChild(root_1, stream_ID.NextNode());
				DebugLocation(62, 40);
				adaptor.AddChild(root_1, stream_block.NextTree());
				DebugLocation(62, 46);
				// /Users/abdullin/MessageContracts.g:62:46: ( declaration )*
				while ( stream_declaration.HasNext )
				{
					DebugLocation(62, 46);
					adaptor.AddChild(root_1, stream_declaration.NextTree());

				}
				stream_declaration.Reset();

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("entity_declaration", 7);
			LeaveRule("entity_declaration", 7);
			LeaveRule_entity_declaration();
	    }
	 	DebugLocation(62, 58);
		} finally { DebugExitRule(GrammarFileName, "entity_declaration"); }
		return retval;

	}
	// $ANTLR end "entity_declaration"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_type_declaration() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_type_declaration() {}

	// $ANTLR start "type_declaration"
	// /Users/abdullin/MessageContracts.g:64:1: type_declaration : ID ( Modifier )? block -> ^( TypeToken ID block ( Modifier )? ) ;
	[GrammarRule("type_declaration")]
	private AstParserRuleReturnScope<object, IToken> type_declaration()
	{
		EnterRule_type_declaration();
		EnterRule("type_declaration", 8);
		TraceIn("type_declaration", 8);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    IToken ID37 = default(IToken);
	    IToken Modifier38 = default(IToken);
	    AstParserRuleReturnScope<object, IToken> block39 = default(AstParserRuleReturnScope<object, IToken>);

	    object ID37_tree = default(object);
	    object Modifier38_tree = default(object);
	    RewriteRuleITokenStream stream_ID=new RewriteRuleITokenStream(adaptor,"token ID");
	    RewriteRuleITokenStream stream_Modifier=new RewriteRuleITokenStream(adaptor,"token Modifier");
	    RewriteRuleSubtreeStream stream_block=new RewriteRuleSubtreeStream(adaptor,"rule block");
		try { DebugEnterRule(GrammarFileName, "type_declaration");
		DebugLocation(64, 56);
		try
		{
			// /Users/abdullin/MessageContracts.g:65:2: ( ID ( Modifier )? block -> ^( TypeToken ID block ( Modifier )? ) )
			DebugEnterAlt(1);
			// /Users/abdullin/MessageContracts.g:65:4: ID ( Modifier )? block
			{
			DebugLocation(65, 4);
			ID37=(IToken)Match(input,ID,Follow._ID_in_type_declaration368);  
			stream_ID.Add(ID37);

			DebugLocation(65, 7);
			// /Users/abdullin/MessageContracts.g:65:7: ( Modifier )?
			int alt7=2;
			try { DebugEnterSubRule(7);
			try { DebugEnterDecision(7, decisionCanBacktrack[7]);
			int LA7_0 = input.LA(1);

			if ((LA7_0==Modifier))
			{
				alt7 = 1;
			}
			} finally { DebugExitDecision(7); }
			switch (alt7)
			{
			case 1:
				DebugEnterAlt(1);
				// /Users/abdullin/MessageContracts.g:65:7: Modifier
				{
				DebugLocation(65, 7);
				Modifier38=(IToken)Match(input,Modifier,Follow._Modifier_in_type_declaration370);  
				stream_Modifier.Add(Modifier38);


				}
				break;

			}
			} finally { DebugExitSubRule(7); }

			DebugLocation(65, 17);
			PushFollow(Follow._block_in_type_declaration373);
			block39=block();
			PopFollow();

			stream_block.Add(block39.Tree);


			{
			// AST REWRITE
			// elements: block, Modifier, ID
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 65:23: -> ^( TypeToken ID block ( Modifier )? )
			{
				DebugLocation(65, 26);
				// /Users/abdullin/MessageContracts.g:65:26: ^( TypeToken ID block ( Modifier )? )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(65, 28);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(TypeToken, "TypeToken"), root_1);

				DebugLocation(65, 38);
				adaptor.AddChild(root_1, stream_ID.NextNode());
				DebugLocation(65, 41);
				adaptor.AddChild(root_1, stream_block.NextTree());
				DebugLocation(65, 47);
				// /Users/abdullin/MessageContracts.g:65:47: ( Modifier )?
				if (stream_Modifier.HasNext)
				{
					DebugLocation(65, 47);
					adaptor.AddChild(root_1, stream_Modifier.NextNode());

				}
				stream_Modifier.Reset();

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("type_declaration", 8);
			LeaveRule("type_declaration", 8);
			LeaveRule_type_declaration();
	    }
	 	DebugLocation(65, 56);
		} finally { DebugExitRule(GrammarFileName, "type_declaration"); }
		return retval;

	}
	// $ANTLR end "type_declaration"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_member() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_member() {}

	// $ANTLR start "member"
	// /Users/abdullin/MessageContracts.g:67:1: member : ( ID ID -> ^( MemberToken ID ID ) | ID -> ^( FragmentReference ID ) );
	[GrammarRule("member")]
	private AstParserRuleReturnScope<object, IToken> member()
	{
		EnterRule_member();
		EnterRule("member", 9);
		TraceIn("member", 9);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    IToken ID40 = default(IToken);
	    IToken ID41 = default(IToken);
	    IToken ID42 = default(IToken);

	    object ID40_tree = default(object);
	    object ID41_tree = default(object);
	    object ID42_tree = default(object);
	    RewriteRuleITokenStream stream_ID=new RewriteRuleITokenStream(adaptor,"token ID");

		try { DebugEnterRule(GrammarFileName, "member");
		DebugLocation(67, 1);
		try
		{
			// /Users/abdullin/MessageContracts.g:68:2: ( ID ID -> ^( MemberToken ID ID ) | ID -> ^( FragmentReference ID ) )
			int alt8=2;
			try { DebugEnterDecision(8, decisionCanBacktrack[8]);
			int LA8_0 = input.LA(1);

			if ((LA8_0==ID))
			{
				int LA8_1 = input.LA(2);

				if ((LA8_1==ID))
				{
					alt8 = 1;
				}
				else if (((LA8_1>=37 && LA8_1<=38)))
				{
					alt8 = 2;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 8, 1, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 8, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(8); }
			switch (alt8)
			{
			case 1:
				DebugEnterAlt(1);
				// /Users/abdullin/MessageContracts.g:68:4: ID ID
				{
				DebugLocation(68, 4);
				ID40=(IToken)Match(input,ID,Follow._ID_in_member398);  
				stream_ID.Add(ID40);

				DebugLocation(68, 7);
				ID41=(IToken)Match(input,ID,Follow._ID_in_member400);  
				stream_ID.Add(ID41);



				{
				// AST REWRITE
				// elements: ID, ID
				// token labels: 
				// rule labels: retval
				// token list labels: 
				// rule list labels: 
				// wildcard labels: 
				retval.Tree = root_0;
				RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

				root_0 = (object)adaptor.Nil();
				// 68:10: -> ^( MemberToken ID ID )
				{
					DebugLocation(68, 13);
					// /Users/abdullin/MessageContracts.g:68:13: ^( MemberToken ID ID )
					{
					object root_1 = (object)adaptor.Nil();
					DebugLocation(68, 15);
					root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(MemberToken, "MemberToken"), root_1);

					DebugLocation(68, 27);
					adaptor.AddChild(root_1, stream_ID.NextNode());
					DebugLocation(68, 30);
					adaptor.AddChild(root_1, stream_ID.NextNode());

					adaptor.AddChild(root_0, root_1);
					}

				}

				retval.Tree = root_0;
				}

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// /Users/abdullin/MessageContracts.g:69:4: ID
				{
				DebugLocation(69, 4);
				ID42=(IToken)Match(input,ID,Follow._ID_in_member415);  
				stream_ID.Add(ID42);



				{
				// AST REWRITE
				// elements: ID
				// token labels: 
				// rule labels: retval
				// token list labels: 
				// rule list labels: 
				// wildcard labels: 
				retval.Tree = root_0;
				RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

				root_0 = (object)adaptor.Nil();
				// 69:7: -> ^( FragmentReference ID )
				{
					DebugLocation(69, 10);
					// /Users/abdullin/MessageContracts.g:69:10: ^( FragmentReference ID )
					{
					object root_1 = (object)adaptor.Nil();
					DebugLocation(69, 12);
					root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(FragmentReference, "FragmentReference"), root_1);

					DebugLocation(69, 30);
					adaptor.AddChild(root_1, stream_ID.NextNode());

					adaptor.AddChild(root_0, root_1);
					}

				}

				retval.Tree = root_0;
				}

				}
				break;

			}
			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("member", 9);
			LeaveRule("member", 9);
			LeaveRule_member();
	    }
	 	DebugLocation(70, 1);
		} finally { DebugExitRule(GrammarFileName, "member"); }
		return retval;

	}
	// $ANTLR end "member"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_block() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_block() {}

	// $ANTLR start "block"
	// /Users/abdullin/MessageContracts.g:73:1: block : lc= '(' ( member ( ',' member )* )? ')' ( representation )? -> ^( BlockToken[$lc,\"Block\"] ( member )* ( representation )? ) ;
	[GrammarRule("block")]
	private AstParserRuleReturnScope<object, IToken> block()
	{
		EnterRule_block();
		EnterRule("block", 10);
		TraceIn("block", 10);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    IToken lc = default(IToken);
	    IToken char_literal44 = default(IToken);
	    IToken char_literal46 = default(IToken);
	    AstParserRuleReturnScope<object, IToken> member43 = default(AstParserRuleReturnScope<object, IToken>);
	    AstParserRuleReturnScope<object, IToken> member45 = default(AstParserRuleReturnScope<object, IToken>);
	    AstParserRuleReturnScope<object, IToken> representation47 = default(AstParserRuleReturnScope<object, IToken>);

	    object lc_tree = default(object);
	    object char_literal44_tree = default(object);
	    object char_literal46_tree = default(object);
	    RewriteRuleITokenStream stream_36=new RewriteRuleITokenStream(adaptor,"token 36");
	    RewriteRuleITokenStream stream_37=new RewriteRuleITokenStream(adaptor,"token 37");
	    RewriteRuleITokenStream stream_38=new RewriteRuleITokenStream(adaptor,"token 38");
	    RewriteRuleSubtreeStream stream_member=new RewriteRuleSubtreeStream(adaptor,"rule member");
	    RewriteRuleSubtreeStream stream_representation=new RewriteRuleSubtreeStream(adaptor,"rule representation");
		try { DebugEnterRule(GrammarFileName, "block");
		DebugLocation(73, 4);
		try
		{
			// /Users/abdullin/MessageContracts.g:74:5: (lc= '(' ( member ( ',' member )* )? ')' ( representation )? -> ^( BlockToken[$lc,\"Block\"] ( member )* ( representation )? ) )
			DebugEnterAlt(1);
			// /Users/abdullin/MessageContracts.g:74:9: lc= '(' ( member ( ',' member )* )? ')' ( representation )?
			{
			DebugLocation(74, 11);
			lc=(IToken)Match(input,36,Follow._36_in_block443);  
			stream_36.Add(lc);

			DebugLocation(75, 13);
			// /Users/abdullin/MessageContracts.g:75:13: ( member ( ',' member )* )?
			int alt10=2;
			try { DebugEnterSubRule(10);
			try { DebugEnterDecision(10, decisionCanBacktrack[10]);
			int LA10_0 = input.LA(1);

			if ((LA10_0==ID))
			{
				alt10 = 1;
			}
			} finally { DebugExitDecision(10); }
			switch (alt10)
			{
			case 1:
				DebugEnterAlt(1);
				// /Users/abdullin/MessageContracts.g:75:14: member ( ',' member )*
				{
				DebugLocation(75, 14);
				PushFollow(Follow._member_in_block458);
				member43=member();
				PopFollow();

				stream_member.Add(member43.Tree);
				DebugLocation(75, 21);
				// /Users/abdullin/MessageContracts.g:75:21: ( ',' member )*
				try { DebugEnterSubRule(9);
				while (true)
				{
					int alt9=2;
					try { DebugEnterDecision(9, decisionCanBacktrack[9]);
					int LA9_0 = input.LA(1);

					if ((LA9_0==38))
					{
						alt9 = 1;
					}


					} finally { DebugExitDecision(9); }
					switch ( alt9 )
					{
					case 1:
						DebugEnterAlt(1);
						// /Users/abdullin/MessageContracts.g:75:22: ',' member
						{
						DebugLocation(75, 22);
						char_literal44=(IToken)Match(input,38,Follow._38_in_block461);  
						stream_38.Add(char_literal44);

						DebugLocation(75, 26);
						PushFollow(Follow._member_in_block463);
						member45=member();
						PopFollow();

						stream_member.Add(member45.Tree);

						}
						break;

					default:
						goto loop9;
					}
				}

				loop9:
					;

				} finally { DebugExitSubRule(9); }


				}
				break;

			}
			} finally { DebugExitSubRule(10); }

			DebugLocation(76, 9);
			char_literal46=(IToken)Match(input,37,Follow._37_in_block477);  
			stream_37.Add(char_literal46);

			DebugLocation(76, 13);
			// /Users/abdullin/MessageContracts.g:76:13: ( representation )?
			int alt11=2;
			try { DebugEnterSubRule(11);
			try { DebugEnterDecision(11, decisionCanBacktrack[11]);
			int LA11_0 = input.LA(1);

			if ((LA11_0==EXPLICIT))
			{
				alt11 = 1;
			}
			} finally { DebugExitDecision(11); }
			switch (alt11)
			{
			case 1:
				DebugEnterAlt(1);
				// /Users/abdullin/MessageContracts.g:76:13: representation
				{
				DebugLocation(76, 13);
				PushFollow(Follow._representation_in_block479);
				representation47=representation();
				PopFollow();

				stream_representation.Add(representation47.Tree);

				}
				break;

			}
			} finally { DebugExitSubRule(11); }



			{
			// AST REWRITE
			// elements: member, representation
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 77:9: -> ^( BlockToken[$lc,\"Block\"] ( member )* ( representation )? )
			{
				DebugLocation(77, 12);
				// /Users/abdullin/MessageContracts.g:77:12: ^( BlockToken[$lc,\"Block\"] ( member )* ( representation )? )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(77, 14);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(BlockToken, lc, "Block"), root_1);

				DebugLocation(77, 38);
				// /Users/abdullin/MessageContracts.g:77:38: ( member )*
				while ( stream_member.HasNext )
				{
					DebugLocation(77, 38);
					adaptor.AddChild(root_1, stream_member.NextTree());

				}
				stream_member.Reset();
				DebugLocation(77, 46);
				// /Users/abdullin/MessageContracts.g:77:46: ( representation )?
				if (stream_representation.HasNext)
				{
					DebugLocation(77, 46);
					adaptor.AddChild(root_1, stream_representation.NextTree());

				}
				stream_representation.Reset();

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("block", 10);
			LeaveRule("block", 10);
			LeaveRule_block();
	    }
	 	DebugLocation(78, 4);
		} finally { DebugExitRule(GrammarFileName, "block"); }
		return retval;

	}
	// $ANTLR end "block"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_representation() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_representation() {}

	// $ANTLR start "representation"
	// /Users/abdullin/MessageContracts.g:80:1: representation : EXPLICIT STRING -> ^( StringRepresentationToken STRING ) ;
	[GrammarRule("representation")]
	private AstParserRuleReturnScope<object, IToken> representation()
	{
		EnterRule_representation();
		EnterRule("representation", 11);
		TraceIn("representation", 11);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    IToken EXPLICIT48 = default(IToken);
	    IToken STRING49 = default(IToken);

	    object EXPLICIT48_tree = default(object);
	    object STRING49_tree = default(object);
	    RewriteRuleITokenStream stream_EXPLICIT=new RewriteRuleITokenStream(adaptor,"token EXPLICIT");
	    RewriteRuleITokenStream stream_STRING=new RewriteRuleITokenStream(adaptor,"token STRING");

		try { DebugEnterRule(GrammarFileName, "representation");
		DebugLocation(80, 57);
		try
		{
			// /Users/abdullin/MessageContracts.g:81:2: ( EXPLICIT STRING -> ^( StringRepresentationToken STRING ) )
			DebugEnterAlt(1);
			// /Users/abdullin/MessageContracts.g:81:4: EXPLICIT STRING
			{
			DebugLocation(81, 4);
			EXPLICIT48=(IToken)Match(input,EXPLICIT,Follow._EXPLICIT_in_representation523);  
			stream_EXPLICIT.Add(EXPLICIT48);

			DebugLocation(81, 13);
			STRING49=(IToken)Match(input,STRING,Follow._STRING_in_representation525);  
			stream_STRING.Add(STRING49);



			{
			// AST REWRITE
			// elements: STRING
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 81:20: -> ^( StringRepresentationToken STRING )
			{
				DebugLocation(81, 23);
				// /Users/abdullin/MessageContracts.g:81:23: ^( StringRepresentationToken STRING )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(81, 25);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(StringRepresentationToken, "StringRepresentationToken"), root_1);

				DebugLocation(81, 51);
				adaptor.AddChild(root_1, stream_STRING.NextNode());

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("representation", 11);
			LeaveRule("representation", 11);
			LeaveRule_representation();
	    }
	 	DebugLocation(81, 57);
		} finally { DebugExitRule(GrammarFileName, "representation"); }
		return retval;

	}
	// $ANTLR end "representation"


	[Conditional("ANTLR_TRACE")]
	protected virtual void EnterRule_extern_declaration() {}
	[Conditional("ANTLR_TRACE")]
	protected virtual void LeaveRule_extern_declaration() {}

	// $ANTLR start "extern_declaration"
	// /Users/abdullin/MessageContracts.g:83:1: extern_declaration : EXTERN STRING ';' -> ^( ExternToken STRING ) ;
	[GrammarRule("extern_declaration")]
	private AstParserRuleReturnScope<object, IToken> extern_declaration()
	{
		EnterRule_extern_declaration();
		EnterRule("extern_declaration", 12);
		TraceIn("extern_declaration", 12);
	    AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
	    retval.Start = (IToken)input.LT(1);

	    object root_0 = default(object);

	    IToken EXTERN50 = default(IToken);
	    IToken STRING51 = default(IToken);
	    IToken char_literal52 = default(IToken);

	    object EXTERN50_tree = default(object);
	    object STRING51_tree = default(object);
	    object char_literal52_tree = default(object);
	    RewriteRuleITokenStream stream_EXTERN=new RewriteRuleITokenStream(adaptor,"token EXTERN");
	    RewriteRuleITokenStream stream_40=new RewriteRuleITokenStream(adaptor,"token 40");
	    RewriteRuleITokenStream stream_STRING=new RewriteRuleITokenStream(adaptor,"token STRING");

		try { DebugEnterRule(GrammarFileName, "extern_declaration");
		DebugLocation(83, 50);
		try
		{
			// /Users/abdullin/MessageContracts.g:84:5: ( EXTERN STRING ';' -> ^( ExternToken STRING ) )
			DebugEnterAlt(1);
			// /Users/abdullin/MessageContracts.g:84:9: EXTERN STRING ';'
			{
			DebugLocation(84, 9);
			EXTERN50=(IToken)Match(input,EXTERN,Follow._EXTERN_in_extern_declaration548);  
			stream_EXTERN.Add(EXTERN50);

			DebugLocation(84, 16);
			STRING51=(IToken)Match(input,STRING,Follow._STRING_in_extern_declaration550);  
			stream_STRING.Add(STRING51);

			DebugLocation(84, 23);
			char_literal52=(IToken)Match(input,40,Follow._40_in_extern_declaration552);  
			stream_40.Add(char_literal52);



			{
			// AST REWRITE
			// elements: STRING
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 84:27: -> ^( ExternToken STRING )
			{
				DebugLocation(84, 30);
				// /Users/abdullin/MessageContracts.g:84:30: ^( ExternToken STRING )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(84, 32);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(ExternToken, "ExternToken"), root_1);

				DebugLocation(84, 44);
				adaptor.AddChild(root_1, stream_STRING.NextNode());

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("extern_declaration", 12);
			LeaveRule("extern_declaration", 12);
			LeaveRule_extern_declaration();
	    }
	 	DebugLocation(84, 50);
		} finally { DebugExitRule(GrammarFileName, "extern_declaration"); }
		return retval;

	}
	// $ANTLR end "extern_declaration"
	#endregion Rules


	#region Follow sets
	private static class Follow
	{
		public static readonly BitSet _declaration_in_program117 = new BitSet(new ulong[]{0x204580842UL});
		public static readonly BitSet _modifier_declaration_in_declaration130 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _frag_declaration_in_declaration135 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _type_declaration_in_declaration140 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _entity_declaration_in_declaration145 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _namespace_declaration_in_declaration150 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _extern_declaration_in_declaration156 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _using_declaration_in_declaration161 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _NAMESPACE_in_namespace_declaration175 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_namespace_declaration178 = new BitSet(new ulong[]{0x18000000000UL});
		public static readonly BitSet _39_in_namespace_declaration181 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_namespace_declaration183 = new BitSet(new ulong[]{0x18000000000UL});
		public static readonly BitSet _40_in_namespace_declaration188 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _USING_in_using_declaration218 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_using_declaration221 = new BitSet(new ulong[]{0x18000000000UL});
		public static readonly BitSet _39_in_using_declaration224 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_using_declaration226 = new BitSet(new ulong[]{0x18000000000UL});
		public static readonly BitSet _40_in_using_declaration231 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _CONST_in_frag_declaration255 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_frag_declaration257 = new BitSet(new ulong[]{0x20000000000UL});
		public static readonly BitSet _41_in_frag_declaration259 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_frag_declaration261 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_frag_declaration263 = new BitSet(new ulong[]{0x10000000000UL});
		public static readonly BitSet _40_in_frag_declaration265 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _IF_in_modifier_declaration292 = new BitSet(new ulong[]{0x1000000UL});
		public static readonly BitSet _Modifier_in_modifier_declaration294 = new BitSet(new ulong[]{0x20000000000UL});
		public static readonly BitSet _41_in_modifier_declaration296 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_modifier_declaration298 = new BitSet(new ulong[]{0x14000000000UL});
		public static readonly BitSet _38_in_modifier_declaration301 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_modifier_declaration303 = new BitSet(new ulong[]{0x14000000000UL});
		public static readonly BitSet _40_in_modifier_declaration307 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _INTERFACE_in_entity_declaration331 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_entity_declaration333 = new BitSet(new ulong[]{0x1000000000UL});
		public static readonly BitSet _block_in_entity_declaration335 = new BitSet(new ulong[]{0x40000000000UL});
		public static readonly BitSet _42_in_entity_declaration337 = new BitSet(new ulong[]{0x80204580840UL});
		public static readonly BitSet _declaration_in_entity_declaration339 = new BitSet(new ulong[]{0x80204580840UL});
		public static readonly BitSet _43_in_entity_declaration342 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _ID_in_type_declaration368 = new BitSet(new ulong[]{0x1001000000UL});
		public static readonly BitSet _Modifier_in_type_declaration370 = new BitSet(new ulong[]{0x1000000000UL});
		public static readonly BitSet _block_in_type_declaration373 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _ID_in_member398 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _ID_in_member400 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _ID_in_member415 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _36_in_block443 = new BitSet(new ulong[]{0x2000080000UL});
		public static readonly BitSet _member_in_block458 = new BitSet(new ulong[]{0x6000000000UL});
		public static readonly BitSet _38_in_block461 = new BitSet(new ulong[]{0x80000UL});
		public static readonly BitSet _member_in_block463 = new BitSet(new ulong[]{0x6000000000UL});
		public static readonly BitSet _37_in_block477 = new BitSet(new ulong[]{0x402UL});
		public static readonly BitSet _representation_in_block479 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _EXPLICIT_in_representation523 = new BitSet(new ulong[]{0x20000000UL});
		public static readonly BitSet _STRING_in_representation525 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _EXTERN_in_extern_declaration548 = new BitSet(new ulong[]{0x20000000UL});
		public static readonly BitSet _STRING_in_extern_declaration550 = new BitSet(new ulong[]{0x10000000000UL});
		public static readonly BitSet _40_in_extern_declaration552 = new BitSet(new ulong[]{0x2UL});
	}
	#endregion Follow sets
}

} // namespace  MessageContracts 
